"use client";
import { useState } from "react";
import type { MarketEvent } from "@/lib/market-odds";
export function OddsBoard({ events }: { events: MarketEvent[] }) {
  const [query, setQuery] = useState(""); const [source, setSource] = useState("All");
  const visible = events.filter((e) => (source === "All" || e.source === source) && e.title.toLowerCase().includes(query.toLowerCase().trim()));
  return <><div className="my-8 flex flex-wrap gap-4 border border-border bg-card p-4"><label className="flex-1 text-sm">Search matches<input type="search" value={query} onChange={(e) => setQuery(e.target.value)} className="mt-2 w-full rounded-none border border-input bg-background p-3" placeholder="Team or match name…" /></label><label className="text-sm">Source<select value={source} onChange={(e) => setSource(e.target.value)} className="mt-2 block rounded-none border border-input bg-background p-3">{["All", "Kalshi", "Polymarket"].map((s) => <option key={s}>{s}</option>)}</select></label></div>
    <p role="status" className="mb-4 font-mono text-xs uppercase tracking-widest text-muted-foreground">{visible.length} markets</p>
    <div className="grid gap-5 lg:grid-cols-2">{visible.map((event, i) => <article key={`${event.source}-${i}`} className="relative overflow-hidden border border-border border-t-2 border-t-primary bg-card p-5 text-card-foreground transition-colors hover:border-primary/60 sm:p-6"><p className="inline-block border border-primary/30 bg-primary/10 px-2 py-1 font-mono text-[10px] font-bold uppercase tracking-widest text-primary">According to {event.source}</p><h2 className="mt-4 text-xl font-extrabold tracking-tight">{event.title}</h2><div className="mt-4 space-y-2">{event.quotes.map((quote, j) => <div key={j} className="flex items-center justify-between gap-4 border-b border-border bg-muted/50 p-3 text-sm last:border-0"><span>{quote.label}</span><span className="shrink-0 text-right font-mono text-2xl font-bold tracking-tight text-primary">{quote.price == null || quote.price === 0 ? "No quote" : `${quote.price.toFixed(1)}¢`}<span className="block text-[10px] font-normal text-muted-foreground">{quote.basis}</span></span></div>)}</div><details className="mt-4 text-xs text-muted-foreground"><summary className="cursor-pointer">Market rules</summary><p className="mt-2 whitespace-pre-line">{event.rules || "See source for settlement rules."}</p></details><a href={event.url} target="_blank" rel="noopener noreferrer" className="mt-5 inline-block border border-primary/40 px-3 py-2 font-mono text-xs font-bold uppercase tracking-wide text-primary transition-colors hover:bg-primary hover:text-primary-foreground">View on {event.source} →</a></article>)}</div>
    {!visible.length && <p className="py-10 text-center text-muted-foreground">No available markets match this search. Coverage varies by source.</p>}
  </>;
}
